version: '2'
services:
  redis:
    image: redis
  db:
    #env_file: .env
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/var/www/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    # sources environment variable configuration for our app
    env_file: .env
    environment:
      RAILS_ENV: $RAILS_ENV
